sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install: gem install bundler -v 1.15.4
install: bundle install --jobs=3 --retry=3 --path=vendor/bundle
cache:
  directories: vendor/bundle
script: bundle exec rspec spec
notifications:
  email: false

